version: "3.10"
services:

  db:
    image: postgres:15
    container_name: db_app
    ports:
      - "5432:5432"
    env_file:
      - .env-non-dev

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: stripe_test
    image: stripe_test:latest
    command: [ "/stripe_test/docker/wait-for-it.sh", "db:5432", "--","/stripe_test/docker/app.sh" ]
    ports:
      - 8000:8000
    depends_on:
      - db